### ISSUE TITLE
Can this write the Arduino Bootloader

### ISSUE THREAD

**Issue by Protoneer** [adafruit/Adafruit_DAP#1]
I have hooked this up like suggested here : https://learn.adafruit.com/programming-an-m0-using-an-arduino

Now I am trying to write the boot-loader to a SAMD21 but for some reason my system does not recognize the boot-loader. The LED blinks/fade as normal but it does not pick up the USB to serial firmware from the boot-loader.

I have successfully written the boot-loader with Atmel Studio but can't get it to work with my Feather ADALogger as the programmer.

Any clues?

**Comment by ladyada** [comment]
in theory, yes - but its kinda of a weird thing to do and if you have a jlink that's by far the best way to do it (with atmel studio) 
beyond that, tech support q's are best posted in the forums - since this isn't a code issue :)
