### ISSUE TITLE
stm32F103VET6 flash failed

### ISSUE THREAD

**Issue by zhizhuowu** [adafruit/Adafruit_DAP#13]
### hi, the example for stm32 flash from SD is not working on feather M0 adalogger with the following error message on serial printf:
Card initialized
Connecting...Adafruit Generic CMSIS-DAP Adapter 123456 v0.1 (S)
invalid response reading reg D (count = 1, value = 4)

that means the 
dap.dap_disconnect()  go through,
but 
dap.dap_connect() can't go through.

May I know whether there is a solution for that? i am using Arduino 1.8.3. does it have anything to do with the version?
Thank you!

**Comment by ladyada** [comment]
it could be a wiring issue, could be speed, we have used it on teensy with success! its hard to debug, please use logic analyzer

**Comment by zhizhuowu** [comment]
hi, Thank you!
May I know the setup you used to test it? I think it can be the speed. 
Thank you for your help.
