### ISSUE TITLE
Error when compiling flash_from_header

### ISSUE THREAD

**Issue by LordMurillo** [adafruit/Adafruit_DAP#31]
When trying to compile it displays the error:

Compiling sketch...
"C:\\Users\\XXXXX\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-IC:\\Users\\XXXXX\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.4\\cores\\arduino" "-IC:\\Users\\XXXXX\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\avr\\1.8.4\\variants\\standard" "-IC:\\Users\\XXXXX\\Documentos\\Arduino\\libraries\\Adafruit_DAP_library" "C:\\Users\\XXXXX\\AppData\\Local\\Temp\\arduino-sketch-2ABE47F1DFA61A43594E3B869F7E9C00\\sketch\\flash_from_header.ino.cpp" -o "C:\\Users\\XXXXX\\AppData\\Local\\Temp\\arduino-sketch-2ABE47F1DFA61A43594E3B869F7E9C00\\sketch\\flash_from_header.ino.cpp.o"
In file included from C:\Users\XXXXX\\Documentos\Arduino\flash_from_header\flash_from_header.ino:2:0:
C:\Users\XXXXX\\Documentos\Arduino\flash_from_header\2772cipy.h:21789:1: error: too many initializers for 'const uint8_t [0] {aka const unsigned char [0]}'
 };
 ^
C:\Users\XXXXX\\Documentos\Arduino\flash_from_header\2772cipy.h:21789:1: sorry, unimplemented: non-trivial designated initializers not supported
C:\Users\XXXXX\\Documentos\Arduino\flash_from_header\2772cipy.h:21789:1: sorry, unimplemented: non-trivial designated initializers not supported
C:\Users\XXXXX\\Documentos\Arduino\flash_from_header\2772cipy.h:21789:1: sorry, unimplemented: non-trivial designated initializers not supported
C:\Users\XXXXX\\Documentos\Arduino\flash_from_header\2772cipy.h:21789:1: sorry, unimplemented: non-trivial designated initializers not supported
...

Best regards

**Comment by hathach** [comment]
which board, which example you are compiling ?

**Comment by hathach** [comment]
this repo is mostly tested with samd, I don't think it support avr. Sorry we have no plan to support it either. PR is welcome though.
