### ISSUE TITLE
Flash MKR Bootloader for ATSAMD21G17A.

### ISSUE THREAD

**Issue by HuyNguyen-01** [adafruit/Adafruit_DAP#38]
Hi.
I have designed a custom board based on the Arduino MKR 1500 board.
But I used the ATSAMD21G17A chip instead of the original ATSAMD21G18A.
This causes me to not be able to load the bootloader.
Node:
I added "`{0x10010306, (char *)"SAM D21G17A (Rev E)", 128*1024, 4096},`"   to the "Adafruit_DAP_SAM.cpp" file.

This helped me get the bootloader.

But when I plug the USB cable into my custom board, I don't see any USB PORT appearing.
I think the Flash is different between the two chips leading to this error. (128Kb for ATSAMD21G17A; 256Kb for ATSAMD21G18A)

Has anyone had any success or have any ideas?

**Comment by hathach** [comment]
sorry, we don't have the hardware to test with. If you figure it out, feel free to make an PR for the fix.
